name: Minify Workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest      # Docker-based github actions have to run on a linux environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:1.0.3
        with:
          directory: 'src'      # Optional
          output: 'minify/src'  # Optional
          add_suffix: false     # Optional

    